services:
  dotnet_postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
    
  dotnet_rabbitmq:
    image: rabbitmq:3-alpine
    
#  dotnet_minio:
#    image: minio/minio:latest
    
#  dotnet_mongodb:
#    image: mongo:latest
    
#  dotnet_jaeger:
#    image: jaegertracing/all-in-one:latest
#    
  dotnet_main:
    build:
      context: .
      dockerfile: Dotnet.Homeworks.MainProject/Dockerfile
    ports:
      - "5000:8080"
    environment:
      ConnectionStrings__Default: "Host=dotnet_postgres;Port=5432;Username=postgres;Password=postgres;Database=postgres"
    depends_on:
      - dotnet_postgres
    
#  dotnet_mailing:
#    image: dotnet-web
#    
#  dotnet_storage:
#    image: dotnet-web